/**
 * Represents a document stored in the vector store with metadata about mistakes
 */
export interface MistakeDocument {
  /**
   * Unique identifier for the document
   */
  id: string;

  /**
   * The actual content/description of the mistake
   */
  content: string;

  /**
   * Metadata associated with the document
   */
  metadata: MistakeMetadata;

  /**
   * Optional embedding vector (may be generated by the vector store)
   */
  embedding?: number[];
}

/**
 * Metadata associated with a mistake document
 */
export interface MistakeMetadata {
  /**
   * The type of task where the mistake occurred
   */
  taskType: string;

  /**
   * Timestamp when the mistake was recorded
   */
  timestamp: Date;

  /**
   * Optional severity level of the mistake
   */
  severity?: 'low' | 'medium' | 'high' | 'critical';

  /**
   * Optional tags for additional categorization
   */
  tags?: string[];

  /**
   * Optional context about the mistake
   */
  context?: string;

  /**
   * Optional solution or correction
   */
  solution?: string;

  /**
   * Any additional custom metadata
   */
  [key: string]: unknown;
}
